### ISSUE TITLE
Create schedule jobs to pause resources for the night with manual dispatch to wake them up.

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-aws-containers#5]
currently RDS and ECS, everything is running 24/7 in dev which incurs cost,
write a schedule job in GHA which pauses all these services during night time.

**Comment by DerekRoberts** [comment]
@mishraomp Good idea!  Everything in PRs could be dialed down at 5 PM, for example.  Plus complete removal for anything over a few days old.

**Comment by mishraomp** [comment]
completed
